In [26]:
import numpy as np
import matplotlib.pyplot as plt
import time

In [59]:
m = np.zeros((15, 15), dtype=bool)
m[1:4, 3] = True
m[3, 2] = True
m[2, 1] = True
plt.imshow(m)

In [54]:
def update(grid):
    # Compute the number of alive neighbors for each cell
    neighbors = (grid[:-2, :-2] + grid[:-2, 1:-1] + grid[:-2, 2:] +
                grid[1:-1, :-2] + grid[1:-1, 2:] +
                grid[2:, :-2] + grid[2:, 1:-1] + grid[2:, 2:])

    # Apply the Game of Life rules
    birth = (neighbors == 3) & (grid[1:-1, 1:-1] == 0)
    survive = ((neighbors == 2) | (neighbors == 3)) & (grid[1:-1, 1:-1] == 1)
    grid[...] = 0
    grid[1:-1, 1:-1][birth | survive] = 1
    return grid

In [42]:
from scipy import signal
a = np.random.randint(2, size=(7, 7), dtype=np.int32)
a

array([[0, 1, 1, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 0, 1, 1],
       [0, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 0, 0],
       [0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 0]], dtype=int32)

In [45]:
filt = np.array([[1, 1, 1], [1, 0, 1], [1, 1, 1]])
filt

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [49]:
signal.convolve(a, filt)[1:-1,1:-1]

array([[3, 3, 4, 2, 4, 1, 2],
       [3, 4, 6, 3, 6, 3, 4],
       [2, 4, 5, 3, 6, 4, 4],
       [3, 5, 5, 5, 6, 4, 3],
       [2, 5, 6, 6, 5, 5, 3],
       [3, 4, 5, 7, 6, 4, 2],
       [1, 2, 3, 3, 4, 3, 2]])

In [29]:
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython import display
from functools import partial

# Turn off matplotlib plot in Notebook
plt.ioff()

In [60]:
# Create an initial grid with some cells set to 1
m = np.zeros((10, 10))
m[1:4, 3] = 1
m[3, 2] = 1
m[2, 1] = 1

fig, ax = plt.subplots()
im = plt.imshow(m)

def next_frame(i):
    global m
    m = update(m)
    im.set_array(m)
    return im

anim = FuncAnimation(fig, partial(next_frame), frames=100, interval=150, blit=False)

video = anim.to_html5_video()
html = display.HTML(video)
display.display(html)
plt.close()